name: "Kafka Cluster Creation"
on: workflow_dispatch
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 CONFLUENT_CLOUD_API_KEY: ${{ secrets.CCLOUD_API_KEY }}
 CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CCLOUD_API_SECRET }}
 TF_VAR_tenant_id: ${{ secrets.AZ_TENANT_ID }}
 TF_VAR_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
 TF_VAR_client_id: ${{ secrets.AZ_CLIENT_ID }}
 TF_VAR_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./private-link/confluent
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.7
     - name: Terraform init
       id: init
       run: terraform init
     - name: Terraform format
       id: fmt
       run: terraform fmt -check
     - name: Terraform validate
       id: validate
       run: terraform validate
     - name: Terraform plan
       id: plan
       run: terraform plan -input=false
       continue-on-error: true
     - name: Terraform Plan Status
       if: steps.plan.outcome == 'failure'
       run: exit 1
     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false